name: Build and Publish go-code-tree

on:
  push:
    tags:
      - 'v*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          **/go.sum
          **/go.mod
          ${{ github.workspace }}/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum', '**/go.mod') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ hashFiles('**/go.mod') }}

    - name: Get dependencies
      run: go mod tidy

    - name: Format code
      run: gofmt -s -w .

    - name: Run tests
      run: go test ./...

    - name: Build for Linux
      run: |
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-linux cmd/go-code-tree-imp/main.go
        GOOS=linux GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-fn-linux cmd/go-code-tree-fn/main.go

    - name: Build for macOS (amd64)
      run: |
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-macos-intel cmd/go-code-tree-imp/main.go
        GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-fn-macos-intel cmd/go-code-tree-fn/main.go

    - name: Build for macOS (arm64)
      run: |
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o bin/go-code-tree-macos-arm cmd/go-code-tree-imp/main.go
        GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" -o bin/go-code-tree-fn-macos-arm cmd/go-code-tree-fn/main.go

    - name: Build for Windows
      run: |
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-windows.exe cmd/go-code-tree-imp/main.go
        GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o bin/go-code-tree-fn-windows.exe cmd/go-code-tree-fn/main.go
  
    - name: Upload build artifact for Linux
      uses: actions/upload-artifact@v4
      with:
        name: go-code-tree-linux
        path: bin/go-code-tree*-linux

    - name: Upload build artifact for macOS (intel)
      uses: actions/upload-artifact@v4
      with:
        name: go-code-tree-macos-intel
        path: bin/go-code-tree*-macos-intel

    - name: Upload build artifact for macOS (arm64)
      uses: actions/upload-artifact@v4
      with:
        name: go-code-tree-macos-arm
        path: bin/go-code-tree*-macos-arm

    - name: Upload build artifact for Windows
      uses: actions/upload-artifact@v4
      with:
        name: go-code-tree-windows
        path: bin/go-code-tree*-windows.exe

    - name: Create Release
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        name: "Release: ${{ github.ref }}"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: false
        allowUpdates: false

    - name: Upload binaries to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        file: ./bin/go-code-tree*
        file_glob: true
